[build]
  publish = "docs"
  command = """
    echo "Setting up Go environment..." && \
    export GOPATH=/opt/buildhome/go && \
    export GOBIN=/opt/buildhome/go/bin && \
    export PATH=$PATH:$GOBIN && \
    echo "Installing docute..." && \
    go install github.com/JackalLabs/docute@latest && \
    echo "Creating directories..." && \
    mkdir -p docs/dist && \
    cd docs && \
    echo "Initializing docute..." && \
    docute init && \
    echo "Running docute generate..." && \
    docute generate && \
    echo "Generated files:" && \
    ls -la
  """

[build.environment]
  GO_VERSION = "1.22.1"
  GOPATH = "/opt/buildhome/go"
  GOBIN = "/opt/buildhome/go/bin"

[[redirects]]
  from = "/*"
  to = "/README.md"
  status = 200
